@echo off
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_0.inp"
"C:s\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_0.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_1.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_1.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_2.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_2.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_3.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_3.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_4.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_4.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_5.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_5.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_6.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_6.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_7.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_7.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_8.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_8.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_9.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_9.fst"
"C:\Users\lsethura\Documents\OpenMDAO\Turbsim\bin\TurbSim_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\Turbsim_inputs\Turbsim_input_file_8ms_row_0_seed_10.inp"
"C:\Program Files\FAST\bin\FAST_x64.exe"  "C:\Users\lsethura\OPENMDAO\UQ_Scripting\Row_0_BIN_1\FAST\Sobol_row0_seed_10.fst"


